name: Org CI 3

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, from org
        env:
          test-reg: $registry-url(npm)
          test-reg2: $registry-url(maven)
          test-reg3: $registry-url(nuget)
          test-bad: $registry-url(bob)
